#!/bin/bash
if   [ $1 = "v1" ]; then sudo rfcomm connect hci0 00:81:F9:08:A1:72;
elif [ $1 = "v2" ]; then sudo rfcomm connect /dev/rfcomm1 00:81:F9:29:BA:98;
elif [ $1 = "va" ]; then sudo rfcomm connect /dev/rfcomm2 00:81:F9:29:EF:80;
elif [ $1 = "vc" ]; then sudo rfcomm connect /dev/rfcomm3 C4:64:E3:EA:75:6D;
fi
