#!/bin/bash
# Actually run the Brainstaves server!!!
#
# Note: to run on Athena, use:
#   nohup python bs_app.py > brainstaves.out &
#
# Version: 2019may08

echo 'Note: use system python in future'
sudo /software/anaconda3/bin/python bs_app.py 80 # Need sudo to run on port 80
