#!/bin/bash
# Actually run the Brainstaves server!!!
#
# Note: to run on Athena, use:
#   nohup python bs_app.py > brainstaves.out &
#
# Version: 2019may08

sudo python bs_app.py 80 # Need sudo to run on port 80
